//: [Previous](@previous)

import Foundation

// MARK: 4. Parse API: What is a Student Location?

/*
 What is a Student Location?
 
 A student location, or StudentLocation object in Parse, is used by "On the Map" to populate its map view with pins and its other views with information submitted by users.
 
 NOTE: Please do not share your actual location or personal information (e.g., real name) for this project. Instead, we advise that you use “dummy” information. To the extent you choose to share your actual location or personal information, you acknowledge that it is subject to our Terms of Use and Privacy Policy, including without limitation the social sharing provisions of these policies, and that it will be accessible by other students within this course which may make use of the information outside Udacity’s control.
 */


/*
 In Parse, each StudentLocation is represented as a collection of key/value pairs:

 // MARK: Key: objectId
 Description: an auto-generated id/key generated by Parse which uniquely identifies a StudentLocation
 Parse Type: String
 Example Value: 8ZExGR5uX8
 
 // MARK:  Key: uniqueKey
 Description: an extra (optional) key used to uniquely identify a StudentLocation; you should populate this value using your Udacity account id
 Parse Type: String
 Example Value: 1234
 
 // MARK:  Key: firstName
 Description: the first name of the student which matches their Udacity profile first name OR an anonymized name hardcoded in your app (see above)
 Parse Type: String
 Example Value: John
 
 // MARK: Key: lastName
 Description: the last name of the student which matches their Udacity profile last name OR an anonymized name hardcoded in your app (see above)
 Parse Type: String
 Example Value: Doe
 
 // MARK: Key: mapString
 Description: the location string used for geocoding the student location
 Parse Type: String
 Example Value: Mountain View, CA
 
 // MARK: Key: mediaURL
 Description: the URL provided by the student
 Parse Type: String
 Example Value: https://udacity.com
 
 // MARK: Key: latitude
 Description: the latitude of the student location (ranges from -90 to 90)
 Parse Type: Number
 Example Value: 37.386052
 
 // MARK: Key: longitude
 Description: the longitude of the student location (ranges from -180 to 180)
 Parse Type: Number
 Example Value: -122.083851
 
 // MARK: Key: createdAt
 Description: the date when the student location was created
 Parse Type: Date
 Example Value: Feb 25, 2015, 01:10
 
 // MARK: Key: updatedAt
 Description: the date when the student location was last updated
 Parse Type: Date
 Example Value: Mar 09, 2015, 23:34
 
 // MARK: Key: ACL
 Description: the Parse access and control list (ACL), i.e. permissions, for this StudentLocation entry
 Parse Type: ACL
 Example Value: Public Read and Write
 
 When you are parsing StudentLocations, the Parse Types can be casted into equivalent Swift types. Any value with the type "Number" may be casted into a floating-point value in Swift. YOU DO NOT HAVE TO WORRY ABOUT PARSING DATE OR ACL TYPES. */

//: [Next](@next)
